version: '3.8'

services:

  php:
    container_name: php_backend
    build:
      context: ./docker/php
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - app

  node:
    container_name: react-frontend
    build:
      context: ./docker/node
    working_dir: /app
    networks:
      - app

  mysql:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: webserver
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app
      
networks:
  app:
    driver: bridge

volumes:
  mysql-data:
    external: false
